version: '3'

services:
  application-service:
    build:
      context: .
      dockerfile: ./application-service/Dockerfile
    container_name: application-service-container
    restart: always
    expose:
      - 8001
    ports:
      - 8001:8001
    networks:
      - spring-cloud-microservices

networks:
  spring-cloud-microservices:
    external: true