global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'api_gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-gateway:8080']
        labels:
          application: 'API Gateway'

  - job_name: 'application_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['application-service:8080']
        labels:
          application: 'Application Service'

  - job_name: 'auth_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['auth-service:8080']
        labels:
          application: 'Auth Service'

  - job_name: 'chart_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['chart-service:8080']
        labels:
          application: 'Chart Service'
  
  - job_name: 'common_data_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['common-data-service:8080']
        labels:
          application: 'Common Data Service'

  - job_name: 'discovery_server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['discovery-server:8080']
        labels:
          application: 'Discovery Server'

  - job_name: 'notification_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['notification-service:8080']
        labels:
          application: 'Notification Service'
  
  - job_name: 'system_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['system-service:8080']
        labels:
          application: 'System Service'